using System;
using System.Linq;
using Generator3.Converter;
using Generator3.Renderer.V2;

namespace Generator3.Renderer.Public;

public static class BitfieldRenderer
{
    public static string Render(GirModel.Bitfield bitfield)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { bitfield.Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(bitfield as GirModel.PlatformDependent)}
    [Flags]
    public enum { bitfield.Name } : ulong
    {{
        {bitfield
            .Members
            .Select(MemberRenderer.Render)
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
