using System;
using System.Linq;
using Generator3.Converter;
using Generator3.Renderer.V2;

namespace Generator3.Renderer.Public;

public static class EnumerationRenderer
{
    public static string Render(GirModel.Enumeration enumeration)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { enumeration.Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(enumeration as GirModel.PlatformDependent)}
    public enum { enumeration.Name } : long
    {{
        {enumeration
            .Members
            .Select(MemberRenderer.Render)
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
