using Generator3.Converter;

namespace Generator3.Renderer.V2.Public;

public static class FundamentalFrameworkRenderer
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { cls.Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(cls as GirModel.PlatformDependent)}
    public partial class { cls.Name } {RenderInheritance(cls)}
    {{
        public {cls.Name}(IntPtr handle) : base(handle) {{ }}
    }}
}}";
    }
    
    private static string RenderInheritance(GirModel.Class cls)
    {
        return cls.Parent is null
            ? $": Fundamental"
            : $": {cls.Parent.GetFullyQualified()}";
    }
}
