using System;
using System.Linq;
using Generator3.Converter;
using Generator3.V2.Renderer.Public;

namespace Generator3.Renderer.V2.Public;

public static class ClassMethodsRenderer
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;
#nullable enable

namespace { cls.Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { cls.Name }
    {{
        {cls.Methods
            .Select(x => MethodRenderer.Render(cls, x))
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
