using Generator3.Converter;

namespace Generator3.Renderer.V2.Public;

public static class InterfaceFrameworkRenderer
{
    public static string Render(GirModel.Interface iface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { iface.Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(iface as GirModel.PlatformDependent)}
    public partial interface { iface.Name } : GLib.IHandle
    {{
        IntPtr GLib.IHandle.Handle
        {{
            get
            {{
                System.Diagnostics.Debug.Assert(
                    condition: GetType().IsAssignableTo(typeof(GObject.Object)),
                    message: $""Interface '{{nameof({iface.Name})}}' can only be implemented on GObject-based classes""
                );

                return ((GObject.Object)this).Handle;
            }}
        }}
    }}
}}";
    }
}
