using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class ClassMethodsRenderer
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { cls.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(cls as GirModel.PlatformDependent)}
    public partial class { cls.Name }
    {{
        {FunctionsRenderer.Render(cls.TypeFunction)}
        {FunctionsRenderer.Render(cls.Functions)}
        {MethodsRenderer.Render(cls.Methods)}
        {ConstructorsRenderer.Render(cls.Constructors)}
    }}
}}";
    }
}
