using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class ClassStructRenderer
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { cls.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(cls as GirModel.PlatformDependent)}
    [StructLayout(LayoutKind.Sequential)]
    public partial struct { cls.GetInternalStructName() }
    {{
        {FieldsRenderer.Render(cls.Fields)}
    }}
}}";
    }
}
