using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class FrameworkExtensionsRenderer
{
    public static string Render(GirModel.Namespace ns)
    {
        return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {ns.GetInternalName()}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public static class Extensions
    {{
        public static T[] MarshalToStructure<T>(this IntPtr[] array)
        {{
            var data = new T[array.Length];
        
            for(int i = 0; i < array.Length; i++)
                data[i] = Marshal.PtrToStructure<T>(array[i]) ?? throw new Exception(""Cant marshal IntPtr[] because one element is not marshallable"");

            return data;
        }}
    }}
}}";
    }
}
