using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class FundamentalClassStructRenderer
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { cls.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(cls as GirModel.PlatformDependent)}
    public partial struct { cls.Name }
    {{
        {FieldsRenderer.Render(cls.Fields)}
    }}
}}";
}
}
