using System.Collections.Generic;
using System.Linq;
using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class GlobalFunctionsRenderer
{
    public static string Render(IEnumerable<GirModel.Function> functions)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { functions.First().Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Functions
    {{
        {FunctionsRenderer.Render(functions)}
    }}
}}";
    }
}
