using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class InterfaceMethodsRenderer
{
    public static string Render(GirModel.Interface iface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { iface.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(iface as GirModel.PlatformDependent)}
    public partial class { iface.Name }
    {{
        {FunctionsRenderer.Render(iface.TypeFunction)}
        {FunctionsRenderer.Render(iface.Functions)}
        {MethodsRenderer.Render(iface.Methods)}
    }}
}}";
    }
}
