using System;
using System.Linq;
using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class RecordDelegatesRenderer
{
    public static string Render(GirModel.Record record)
    {
        return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { record.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial struct { record.GetInternalStructName() }
    {{
        {record.Fields
            .Select(x => x.AnyTypeOrCallback)
            .Where(x => x.IsT1)
            .Select(x => x.AsT1)
            .Select(CallbackRenderer.Render)
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
