using Generator3.Converter;

namespace Generator3.Renderer.V2.Internal;

public static class UnionMethodsRenderer
{
    public static string Render(GirModel.Union union)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { union.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(union as GirModel.PlatformDependent)}
    public partial class { union.Name }
    {{
        {FunctionsRenderer.Render(union.TypeFunction)}
        {FunctionsRenderer.Render(union.Functions)}
        {MethodsRenderer.Render(union.Methods)}
        {ConstructorsRenderer.Render(union.Constructors)}
    }}
}}";
    }
}
