using System;
using System.Linq;
using Generator3.Converter;
using Generator3.Model.V2.Internal;

namespace Generator3.Renderer.V2.Internal;

public static class UnionStructRenderer
{
    public static string Render(GirModel.Union union)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { union.Namespace.GetInternalName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttributeRenderer.Render(union as GirModel.PlatformDependent)}
    [StructLayout(LayoutKind.Explicit)]
    public partial struct { union.GetInternalStructName() }
    {{
        {union.Fields
            .Select(RenderField)
            .Join(Environment.NewLine)}
    }}
}}";
    }

    private static string RenderField(GirModel.Field field)
    {
        var renderableField = RenderableFieldFactory.Create(field);

        return @$"[FieldOffset(0)]{renderableField.Attribute} public {renderableField.NullableTypeName} {renderableField.Name};";
    }
}
