using System;
using System.Collections.Generic;
using System.Linq;
using Generator3.Converter;

namespace Generator3.Renderer.V2.Public;

public static class ConstantsRenderer
{
    public static string Render(IEnumerable<GirModel.Constant> constants)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { constants.First().Namespace.GetPublicName() }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Constants
    {{
        {constants
            .Select(Render)
            .Join(Environment.NewLine)}
    }}
}}";
    }
    
    private static string Render(GirModel.Constant constant)
    {
        var renderableConstant = RenderableConstantFactory.Create(constant);
        
        return @$"
{PlatformSupportAttributeRenderer.Render(constant as GirModel.PlatformDependent)}
public static { renderableConstant.Type } { renderableConstant.Name } = { renderableConstant.Value };";
    }
}
